(()=>{'use strict';
const KEY='kurisagari-adventure-v1';
const rewards={
  treasure:[['🪙','ふるいコイン'],['🧭','ぼうけんコンパス'],['🏺','こだいのつぼ'],['💎','あおいほうせき'],['🗝️','おうごんのカギ'],['📜','ひみつのちず'],['👑','おうさまのかんむり'],['🏆','でんせつのトロフィー'],['💰','でんせつのたから']],
  lake:[['🐟','メダカ'],['🐠','カラフルフィッシュ'],['🐡','ぷくぷくフグ'],['🦀','カニさん'],['🦐','エビちゃん'],['🐙','ちびタコ'],['🦑','イカくん'],['🐬','イルカ'],['🐳','くじら']],
  forest:[['🐿️','リス'],['🐇','うさぎ'],['🦔','ハリネズミ'],['🦊','きつね'],['🦉','ふくろう'],['🦌','こじか'],['🐻','こぐま'],['🐼','パンダ'],['🦄','まぼろしユニコーン']]
};
const themeInfo={
  treasure:{card:'treasure',character:'🏴‍☠️',target:'🧰',speech:s=>`🔑 × ${s}`,done:'パカッ！',prefix:'おたからを みつけた！',toast:'🏴‍☠️ たからさがし！'},
  lake:{card:'lake',character:'🎣',target:'🐟',speech:s=>`🍡 × ${s}`,done:'つれた！',prefix:'おさかなを つった！',toast:'🎣 さかなつり！'},
  forest:{card:'forest',character:'🦊',target:'🦊',speech:s=>`🌰 × ${s}`,done:'なかま！',prefix:'もりの なかまになった！',toast:'🌳 もりへ！'}
};
const base={theme:'treasure',selectedSubtractor:5,unlockedMax:5,stageWins:{5:0,6:0,7:0,8:0,9:0},stars:0,sequence:{5:0,6:0,7:0,8:0,9:0},collection:{treasure:{},lake:{},forest:{}}};
const $=id=>document.getElementById(id);
let state=load(),round=null,phase=1,splitTen=0,splitExtra=0,taken=0,drag=null,book=state.theme,transitionTimer=null;
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...p,stageWins:{...base.stageWins,...(p.stageWins||{})},sequence:{...base.sequence,...(p.sequence||{})},collection:{treasure:{...(p.collection?.treasure||{})},lake:{...(p.collection?.lake||{})},forest:{...(p.collection?.forest||{})}}}}catch{return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function nextProblem(s){const a=[];for(let n=11;n<=9+s;n++)a.push(n);const n=a[state.sequence[s]%a.length];state.sequence[s]++;return{minuend:n,subtractor:s,extra:n-10,remain:10-s,answer:n-s}}
function stages(){const box=$('stageButtons');box.innerHTML='';for(let n=5;n<=9;n++){const locked=n>state.unlockedMax,b=document.createElement('button');b.type='button';b.className='stage-button'+(locked?' locked':'')+(n===state.selectedSubtractor?' active':'');b.disabled=locked;b.innerHTML=locked?`−${n}<small>🔒</small>`:`−${n}<small>${state.stageWins[n]}/3</small>`;b.addEventListener('click',()=>{state.selectedSubtractor=n;save();startRound()});box.appendChild(b)}const w=state.stageWins[state.selectedSubtractor];$('stageTitle').textContent=`−${state.selectedSubtractor} ステージ`;$('stageProgressText').textContent=state.selectedSubtractor===9&&w>=3?'ぜんぶクリア！🎉':state.selectedSubtractor===state.unlockedMax&&state.selectedSubtractor<9?`あと${Math.max(0,3-w)}もんで −${state.selectedSubtractor+1}`:`${w}/3 クリア`}
function applyTheme(){const info=themeInfo[state.theme]||themeInfo.treasure,card=$('gameCard');card.classList.remove('treasure','lake','forest');card.classList.add(info.card);document.querySelectorAll('.theme-button').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$('sceneCharacter').textContent=info.character;$('sceneTarget').textContent=info.target;$('speechBubble').textContent=info.speech(round?.subtractor||state.selectedSubtractor)}
function makeToken(kind='neutral',draggable=false,type=''){const b=document.createElement('button');b.type='button';b.className=`math-token ${kind}${draggable?' draggable':''}`;b.setAttribute('aria-label','まるをうごかす');if(draggable){b.dataset.dragType=type;b.addEventListener('pointerdown',startDrag);b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();autoMove(type,b)}})}return b}
function fill(container,n,kind='neutral',draggable=false,type=''){const c=typeof container==='string'?$(container):container;c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(makeToken(kind,draggable,type))}
function setPhase(n){phase=n;['splitStep','subtractStep','mergeStep','resultStep'].forEach(id=>$(id).classList.add('hidden'));['stepDot1','stepDot2','stepDot3'].forEach(id=>$(id).classList.remove('active','done'));if(n===1){$('splitStep').classList.remove('hidden');$('stepDot1').classList.add('active')}else if(n===2){$('subtractStep').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('active')}else if(n===3){$('mergeStep').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('done');$('stepDot3').classList.add('active')}else{$('resultStep').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('done');$('stepDot3').classList.add('done')}}
function setEquation(html,flash=true){const el=$('liveEquation');el.innerHTML=html;if(flash){el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash')}}
function startRound(){clearTimeout(transitionTimer);cancelDrag();splitTen=0;splitExtra=0;taken=0;round=nextProblem(state.selectedSubtractor);save();applyTheme();stages();$('starCount').textContent=state.stars;$('problemText').textContent=`${round.minuend} − ${round.subtractor}`;$('splitBigNumber').textContent=round.minuend;$('splitTenCount').textContent='0 / 10';$('splitExtraCount').textContent='0';$('splitExtraLabel').textContent='？';$('subtractBadge').textContent=`−${round.subtractor}`;$('subtractExtraBadge').textContent=round.extra;$('takenCount').textContent=`0 / ${round.subtractor}`;$('mergeExtraBadge').textContent=round.extra;$('mergeRemainBadge').textContent=round.remain;$('mergeAnswerBadge').textContent='？';$('unlockMessage').classList.add('hidden');$('autoSplitButton').disabled=false;$('autoTakeButton').disabled=false;$('autoMergeButton').disabled=false;fill('splitSource',round.minuend,'neutral',true,'split');fill('splitTenTokens',0);fill('splitExtraTokens',0);fill('subtractTenTokens',10,'ten',true,'subtract');fill('subtractExtraTokens',round.extra,'extra');renderTakeSlots();fill('mergeExtraTokens',round.extra,'extra');fill('mergeRemainTokens',round.remain,'ten');$('mergeExtraGroup').classList.remove('merged');$('mergeExtraGroup').dataset.dragType='merge';$('mergeExtraGroup').addEventListener('pointerdown',startDrag);$('mergeExtraGroup').tabIndex=0;$('mergeExtraGroup').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();completeMerge()}};$('splitTenTarget').classList.add('pulse');$('splitExtraTarget').classList.remove('pulse','ready');$('subtractTarget').classList.remove('hot');$('mergeTarget').classList.remove('hot','complete');setEquation(`${round.minuend} − ${round.subtractor} = <strong>？</strong>`,false);setPhase(1)}
function renderTakeSlots(){const c=$('takeSlots');c.innerHTML='';for(let i=0;i<round.subtractor;i++){const s=document.createElement('span');s.className='take-slot'+(i<taken?' filled':'');s.textContent=i<taken?'✓':'';c.appendChild(s)}}
function startDrag(e){if(e.button!==undefined&&e.button!==0)return;const el=e.currentTarget,type=el.dataset.dragType;if(!type)return;if((type==='split'&&phase!==1)||(type==='subtract'&&phase!==2)||(type==='merge'&&phase!==3))return;e.preventDefault();cancelDrag();const ghost=el.cloneNode(true);ghost.classList.add('drag-ghost');ghost.removeAttribute('id');document.body.appendChild(ghost);drag={pointerId:e.pointerId,el,type,ghost,x:e.clientX,y:e.clientY};try{el.setPointerCapture(e.pointerId)}catch{}moveGhost(e.clientX,e.clientY);highlightTargets(e.clientX,e.clientY)}
function moveGhost(x,y){if(!drag)return;drag.x=x;drag.y=y;drag.ghost.style.left=`${x}px`;drag.ghost.style.top=`${y}px`}
function pointIn(id,x,y){const r=$(id).getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function highlightTargets(x,y){document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('hot'));if(!drag)return;if(drag.type==='split'){if(pointIn('splitTenTarget',x,y))$('splitTenTarget').classList.add('hot');if(pointIn('splitExtraTarget',x,y))$('splitExtraTarget').classList.add('hot')}else if(drag.type==='subtract'&&pointIn('subtractTarget',x,y))$('subtractTarget').classList.add('hot');else if(drag.type==='merge'&&pointIn('mergeTarget',x,y))$('mergeTarget').classList.add('hot')}
function endDrag(){if(!drag)return;const {type,el,x,y}=drag;let done=false;if(type==='split'){if(pointIn('splitTenTarget',x,y)&&splitTen<10){placeSplit(el,'ten');done=true}else if(pointIn('splitExtraTarget',x,y)&&splitTen===10){placeSplit(el,'extra');done=true}else if(pointIn('splitExtraTarget',x,y)&&splitTen<10){nudge('splitTenTarget')}}else if(type==='subtract'&&pointIn('subtractTarget',x,y)){takeToken(el);done=true}else if(type==='merge'&&pointIn('mergeTarget',x,y)){completeMerge();done=true}if(!done)el.classList.add('shake');setTimeout(()=>el.classList.remove('shake'),300);cancelDrag()}
function cancelDrag(){if(drag?.ghost)drag.ghost.remove();drag=null;document.querySelectorAll('.drop-zone').forEach(z=>z.classList.remove('hot'))}
function nudge(id){const el=$(id);el.classList.remove('nudge');void el.offsetWidth;el.classList.add('nudge')}
function placeSplit(el,where){if(!el||!el.isConnected)return;el.remove();if(where==='ten'){splitTen++;$('splitTenTokens').appendChild(makeToken('ten'));$('splitTenCount').textContent=`${splitTen} / 10`;if(splitTen===10){$('splitTenTarget').classList.remove('pulse');$('splitExtraTarget').classList.add('ready','pulse');setEquation(`${round.minuend} = <span class="ten-text">10</span> + <strong>？</strong>`)}}else{splitExtra++;$('splitExtraTokens').appendChild(makeToken('extra'));$('splitExtraCount').textContent=splitExtra;$('splitExtraLabel').textContent=splitExtra}if(splitTen===10&&splitExtra===round.extra){$('autoSplitButton').disabled=true;$('splitExtraTarget').classList.remove('pulse');setEquation(`${round.minuend} = <span class="ten-text">10</span> + <span class="extra-text">${round.extra}</span>`);transitionTimer=setTimeout(beginSubtract,1000)}}
function beginSubtract(){fill('subtractTenTokens',10,'ten',true,'subtract');taken=0;renderTakeSlots();$('takenCount').textContent=`0 / ${round.subtractor}`;setEquation(`${round.minuend} − ${round.subtractor} = <span class="extra-text">${round.extra}</span> + (10 − ${round.subtractor})`);setPhase(2)}
function takeToken(el){if(phase!==2||taken>=round.subtractor||!el||el.classList.contains('gone'))return;el.classList.add('gone');el.disabled=true;taken++;renderTakeSlots();$('takenCount').textContent=`${taken} / ${round.subtractor}`;const left=10-taken;if(taken<round.subtractor){setEquation(`10 − ${taken} = <span class="ten-text">${left}</span>`,false)}else{$('autoTakeButton').disabled=true;setEquation(`10 − ${round.subtractor} = <span class="ten-text">${round.remain}</span>`);transitionTimer=setTimeout(()=>{setEquation(`${round.minuend} − ${round.subtractor} = <span class="extra-text">${round.extra}</span> + <span class="ten-text">${round.remain}</span>`);setPhase(3)},1000)}}
function completeMerge(){if(phase!==3)return;$('autoMergeButton').disabled=true;$('mergeExtraGroup').classList.add('merged');$('mergeTarget').classList.add('complete');const target=$('mergeFinalTokens');target.innerHTML='';for(let i=0;i<round.extra;i++)target.appendChild(makeToken('extra'));for(let i=0;i<round.remain;i++)target.appendChild(makeToken('ten'));$('mergeAnswerBadge').textContent=round.answer;setEquation(`${round.minuend} − ${round.subtractor} = <span class="extra-text">${round.extra}</span> + <span class="ten-text">${round.remain}</span> = <strong>${round.answer}</strong>`);transitionTimer=setTimeout(finishRound,1100)}
function autoMove(type,el=null){if(type==='split'){const source=$('splitSource').querySelector('.math-token');if(!source)return;if(splitTen<10)placeSplit(source,'ten');else placeSplit(source,'extra')}else if(type==='subtract'){const token=el||[...$('subtractTenTokens').children].find(x=>!x.classList.contains('gone'));if(token)takeToken(token)}else if(type==='merge')completeMerge()}
function finishRound(){setPhase(4);const list=rewards[state.theme],idx=Math.floor(Math.random()*list.length),reward=list[idx],bucket=state.collection[state.theme];bucket[idx]=(bucket[idx]||0)+1;state.stars++;state.stageWins[round.subtractor]=Math.min(3,state.stageWins[round.subtractor]+1);let unlock='';if(round.subtractor===state.unlockedMax&&state.stageWins[round.subtractor]>=3&&state.unlockedMax<9){state.unlockedMax++;unlock=`🎉 −${state.unlockedMax} が ひらいた！`}save();$('starCount').textContent=state.stars;$('resultEquation').innerHTML=`${round.minuend} − ${round.subtractor} = <span class="extra-text">${round.extra}</span> + <span class="ten-text">${round.remain}</span> = <strong>${round.answer}</strong>`;$('rewardEmoji').textContent=reward[0];$('rewardName').textContent=reward[1];$('rewardPrefix').textContent=themeInfo[state.theme].prefix;$('sceneTarget').textContent=reward[0];$('speechBubble').textContent=themeInfo[state.theme].done;$('unlockMessage').textContent=unlock;$('unlockMessage').classList.toggle('hidden',!unlock);stages()}
function toast(text){const t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1400)}
function renderCollection(){const list=rewards[book],owned=state.collection[book]||{},grid=$('collectionGrid');grid.innerHTML='';list.forEach((r,i)=>{const n=owned[i]||0,d=document.createElement('div');d.className='collection-item'+(n?' unlocked':'');d.innerHTML=`<span class="emoji">${r[0]}</span><strong>${n?r[1]:'？？？'}</strong><small>${n?'ゲット！':'まだだよ'}</small>${n?`<span class="collection-count">×${n}</span>`:''}`;grid.appendChild(d)});document.querySelectorAll('.collection-tab').forEach(b=>b.classList.toggle('active',b.dataset.collection===book))}
window.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.pointerId)return;e.preventDefault();moveGhost(e.clientX,e.clientY);highlightTargets(e.clientX,e.clientY)},{passive:false});
window.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.pointerId)endDrag()});window.addEventListener('pointercancel',cancelDrag);window.addEventListener('blur',cancelDrag);
document.querySelectorAll('.theme-button').forEach(b=>b.addEventListener('click',()=>{state.theme=b.dataset.theme;book=state.theme;save();startRound();toast(themeInfo[state.theme].toast)}));
$('autoSplitButton').addEventListener('click',()=>autoMove('split'));$('autoTakeButton').addEventListener('click',()=>autoMove('subtract'));$('autoMergeButton').addEventListener('click',()=>autoMove('merge'));$('nextButton').addEventListener('click',()=>{if(state.stageWins[state.selectedSubtractor]>=3&&state.selectedSubtractor<state.unlockedMax)state.selectedSubtractor++;startRound()});
const dialog=$('collectionDialog');$('collectionButton').addEventListener('click',()=>{book=state.theme;renderCollection();dialog.showModal()});$('closeCollectionButton').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});document.querySelectorAll('.collection-tab').forEach(b=>b.addEventListener('click',()=>{book=b.dataset.collection;renderCollection()}));
startRound();
})();