(()=>{'use strict';
const KEY='kurisagari-adventure-v1';
const rewards=[['🪙','ふるいコイン'],['🧭','ぼうけんコンパス'],['🏺','こだいのつぼ'],['💎','あおいほうせき'],['🗝️','おうごんのカギ'],['📜','ひみつのちず'],['👑','おうさまのかんむり'],['🏆','でんせつのトロフィー'],['💰','でんせつのたから']];
const base={selectedSubtractor:5,unlockedMax:5,stageWins:{5:0,6:0,7:0,8:0,9:0},stars:0,sequence:{5:0,6:0,7:0,8:0,9:0},collection:{treasure:{}}};
const $=id=>document.getElementById(id);let state=load(),round=null,phase='split',extraMoved=0,removed=0,drag=null;
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...p,stageWins:{...base.stageWins,...(p.stageWins||{})},sequence:{...base.sequence,...(p.sequence||{})},collection:{treasure:{...(p.collection?.treasure||{})}}}}catch{return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function makeProblem(s){const a=[];for(let n=11;n<=9+s;n++)a.push(n);const n=a[state.sequence[s]%a.length];state.sequence[s]++;return{minuend:n,subtractor:s,extra:n-10,remain:10-s,answer:n-s}}
function stages(){const box=$('stageButtons');box.innerHTML='';for(let n=5;n<=9;n++){const locked=n>state.unlockedMax,b=document.createElement('button');b.type='button';b.className='stage-button'+(locked?' locked':'')+(n===state.selectedSubtractor?' active':'');b.disabled=locked;b.innerHTML=locked?`−${n}<small>🔒</small>`:`−${n}<small>${state.stageWins[n]}/3</small>`;b.onclick=()=>{state.selectedSubtractor=n;save();start()};box.appendChild(b)}const w=state.stageWins[state.selectedSubtractor];$('stageTitle').textContent=`−${state.selectedSubtractor} の とびら`;$('stageProgressText').textContent=state.selectedSubtractor===9&&w>=3?'ぜんぶクリア！🎉':state.selectedSubtractor===state.unlockedMax&&state.selectedSubtractor<9?`あと${Math.max(0,3-w)}もんで −${state.selectedSubtractor+1}`:`${w}/3 クリア`}
function equation(html){const el=$('equation');el.innerHTML=html;el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash')}
function makeBall(draggable=true,used=false){const b=document.createElement(draggable?'button':'span');if(draggable)b.type='button';b.className='ball same-ball'+(used?' used-ball':'');b.setAttribute('aria-label',used?'とびらにつかった宝石':'宝石をうごかす');if(draggable){b.addEventListener('pointerdown',dragStart);b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();autoMove(b)}})}return b}
function makeHole(){const h=document.createElement('span');h.className='ball-hole';h.setAttribute('aria-label','宝石をとったあと');return h}
function renderSource(n){const c=$('sourceBalls');c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(makeBall(true))}
function appendStatic(id,n,used=false){const c=$(id);for(let i=0;i<n;i++)c.appendChild(makeBall(false,used))}
function visibleSourceCount(){return $('sourceBalls').querySelectorAll('.ball').length}
function updateCounts(){$('sourceCount').textContent=visibleSourceCount();$('extraCount').textContent=`${extraMoved}/${round.extra}`;$('subtractCount').textContent=`${removed}/${round.subtractor}`}
function setHint(step,text){$('hintBadge').textContent=step;$('hintText').textContent=text}
function setStory(text){$('storyText').innerHTML=text}
function methodEquation(answer='？'){return `${round.minuend} − ${round.subtractor} = (10 − ${round.subtractor}) + ${round.extra} = <strong>${answer}</strong>`}
function start(){cancelDrag();round=makeProblem(state.selectedSubtractor);extraMoved=0;removed=0;phase='split';save();stages();$('starCount').textContent=state.stars;$('problemText').textContent=`${round.minuend} − ${round.subtractor}`;$('sourceTitle').textContent=`💎 ${round.minuend}こ`;$('extraNeed').textContent=round.extra;$('subtractNeed').textContent=round.subtractor;$('doorNeed').textContent=round.subtractor;$('answerPanel').classList.add('hidden');$('resultInline').classList.add('hidden');$('extraArea').classList.add('pulse');$('subtractArea').classList.remove('pulse');$('doorVisual').classList.remove('open');$('doorEmoji').textContent='🚪';$('chestEmoji').textContent='🧰';renderSource(round.minuend);$('extraBalls').innerHTML='';$('subtractBalls').innerHTML='';updateCounts();setHint('①',`${round.extra}こ → ふくろへ`);setStory(`🏴‍☠️ 宝のとびらだ！ <strong>💎${round.minuend}こ</strong>ある。<br><span class="story-goal">🔐 とびらをあけるには <strong>${round.subtractor}こ つかう！</strong></span>`);equation(`${round.minuend} − ${round.subtractor} = <strong>？</strong>`)}
function dragStart(e){if(e.button!==undefined&&e.button!==0)return;if(phase!=='split'&&phase!=='subtract')return;const el=e.currentTarget;if(!el.isConnected||!el.classList.contains('ball'))return;e.preventDefault();cancelDrag();const ghost=el.cloneNode(true);ghost.classList.add('drag-ghost');ghost.removeAttribute('id');document.body.appendChild(ghost);drag={id:e.pointerId,el,ghost,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY};moveDrag(e.clientX,e.clientY)}
function moveDrag(x,y){if(!drag)return;drag.x=x;drag.y=y;drag.ghost.style.left=`${x}px`;drag.ghost.style.top=`${y}px`;$('extraArea').classList.remove('hot');$('subtractArea').classList.remove('hot');const target=phase==='split'?'extraArea':'subtractArea';if(pointIn(target,x,y))$(target).classList.add('hot')}
function pointIn(id,x,y){const r=$(id).getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function dragEnd(){if(!drag)return;const {el,x,y,startX,startY}=drag,target=phase==='split'?'extraArea':'subtractArea',distance=Math.hypot(x-startX,y-startY);if(pointIn(target,x,y)||distance<9)autoMove(el);else{el.classList.remove('wrong');void el.offsetWidth;el.classList.add('wrong')}cancelDrag()}
function cancelDrag(){drag?.ghost?.remove();drag=null;$('extraArea')?.classList.remove('hot');$('subtractArea')?.classList.remove('hot')}
function autoMove(el){if(!el||!el.isConnected)return;if(phase==='split')moveToExtra(el);else if(phase==='subtract')moveToSubtract(el)}
function moveToExtra(el){if(extraMoved>=round.extra)return;el.remove();$('extraBalls').appendChild(makeBall(false));extraMoved++;updateCounts();if(extraMoved===round.extra){phase='subtract';$('sourceTitle').textContent='💎 10こ';$('extraArea').classList.remove('pulse');$('subtractArea').classList.add('pulse');setHint('②',`↓ ${round.subtractor}こ とびらに使う`);setStory(`10こに そろった！<br><span class="story-goal">🚪 とびらへ <strong>${round.subtractor}こ</strong> 使おう！</span>`);equation(`${round.minuend} − ${round.subtractor} = (10 − ${round.subtractor}) + ${round.extra}`)}}
function moveToSubtract(el){if(removed>=round.subtractor)return;const hole=makeHole();el.replaceWith(hole);$('subtractBalls').appendChild(makeBall(false,true));removed++;updateCounts();$('sourceTitle').textContent=`💎 のこり ${visibleSourceCount()}こ`;if(removed===round.subtractor){phase='answer';$('subtractArea').classList.remove('pulse');setHint('③','のこった宝石は？');setStory(`🚪に <strong>${round.subtractor}こ</strong> 使った！<br><span class="story-goal">左の宝石 ＋ ふくろの宝石 = いくつ？</span>`);equation(methodEquation());showAnswers()}}
function showAnswers(){const panel=$('answerPanel'),box=$('answers');box.innerHTML='';for(let n=1;n<=9;n++){const b=document.createElement('button');b.type='button';b.className='answer-button';b.textContent=n;b.addEventListener('click',()=>chooseAnswer(n,b));box.appendChild(b)}panel.classList.remove('hidden')}
function chooseAnswer(n,b){if(phase!=='answer')return;if(n!==round.answer){b.classList.remove('wrong');void b.offsetWidth;b.classList.add('wrong');return}phase='result';b.classList.add('correct');[...$('answers').children].forEach(x=>x.disabled=true);finish()}
function finish(){equation(methodEquation(round.answer));const idx=Math.floor(Math.random()*rewards.length),reward=rewards[idx],bucket=state.collection.treasure;bucket[idx]=(bucket[idx]||0)+1;state.stars++;state.stageWins[round.subtractor]=Math.min(3,state.stageWins[round.subtractor]+1);let unlock='';if(round.subtractor===state.unlockedMax&&state.stageWins[round.subtractor]>=3&&state.unlockedMax<9){state.unlockedMax++;unlock=`🎉 −${state.unlockedMax} の とびらが ひらいた！`}save();$('starCount').textContent=state.stars;$('resultEquation').innerHTML=methodEquation(round.answer);$('resultBalls').innerHTML='';appendStatic('resultBalls',round.answer,false);$('rewardEmoji').textContent=reward[0];$('rewardName').textContent=reward[1];$('doorVisual').classList.add('open');$('doorEmoji').textContent='✨';$('chestEmoji').textContent='🧰✨';setStory(`🎉 せいかい！ とびらが ひらいた！<br><span class="story-goal">${reward[0]} ${reward[1]} を ゲット！</span>`);$('unlockMessage').textContent=unlock;$('unlockMessage').classList.toggle('hidden',!unlock);$('resultInline').classList.remove('hidden');stages()}
function renderCollection(){const owned=state.collection.treasure||{},grid=$('collectionGrid');grid.innerHTML='';rewards.forEach((r,i)=>{const n=owned[i]||0,d=document.createElement('div');d.className='collection-item'+(n?' unlocked':'');d.innerHTML=`<span class="emoji">${r[0]}</span><strong>${n?r[1]:'？？？'}</strong><small>${n?'ゲット！':'まだだよ'}</small>${n?`<span class="collection-count">×${n}</span>`:''}`;grid.appendChild(d)})}
window.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.id){e.preventDefault();moveDrag(e.clientX,e.clientY)}},{passive:false});window.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.id)dragEnd()});window.addEventListener('pointercancel',cancelDrag);window.addEventListener('blur',cancelDrag);
$('nextButton').onclick=start;const dialog=$('collectionDialog');$('collectionButton').onclick=()=>{renderCollection();dialog.showModal()};$('closeCollectionButton').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};start();
})();