(()=>{'use strict';
const KEY='kurisagari-adventure-v1';
const rewards={treasure:[['🪙','ふるいコイン'],['🧭','ぼうけんコンパス'],['🏺','こだいのつぼ'],['💎','あおいほうせき'],['🗝️','おうごんのカギ'],['📜','ひみつのちず'],['👑','おうさまのかんむり'],['🏆','でんせつのトロフィー'],['💰','でんせつのたから']],lake:[['🐟','メダカ'],['🐠','カラフルフィッシュ'],['🐡','ぷくぷくフグ'],['🦀','カニさん'],['🦐','エビちゃん'],['🐙','ちびタコ'],['🦑','イカくん'],['🐬','イルカ'],['🐳','くじら']],forest:[['🐿️','リス'],['🐇','うさぎ'],['🦔','ハリネズミ'],['🦊','きつね'],['🦉','ふくろう'],['🦌','こじか'],['🐻','こぐま'],['🐼','パンダ'],['🦄','まぼろしユニコーン']]};
const themes={treasure:{card:'treasure',hero:'🏴‍☠️',target:'🧰',tool:'🗝️',prefix:'おたからを みつけた！',done:'パカッ！'},lake:{card:'lake',hero:'🎣',target:'🐟',tool:'🍡',prefix:'おさかなを つった！',done:'つれた！'},forest:{card:'forest',hero:'🦊',target:'🦊',tool:'🌰',prefix:'もりの なかまになった！',done:'なかま！'}};
const base={theme:'treasure',selectedSubtractor:5,unlockedMax:5,stageWins:{5:0,6:0,7:0,8:0,9:0},stars:0,sequence:{5:0,6:0,7:0,8:0,9:0},collection:{treasure:{},lake:{},forest:{}}};
const $=id=>document.getElementById(id);let state=load(),round,phase=1,drag=null,book=state.theme,timers=[];
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...p,stageWins:{...base.stageWins,...(p.stageWins||{})},sequence:{...base.sequence,...(p.sequence||{})},collection:{treasure:{...(p.collection?.treasure||{})},lake:{...(p.collection?.lake||{})},forest:{...(p.collection?.forest||{})}}}}catch{return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}function later(fn,ms){const id=setTimeout(fn,ms);timers.push(id);return id}function clearTimers(){timers.forEach(clearTimeout);timers=[]}
function makeProblem(s){const arr=[];for(let n=11;n<=9+s;n++)arr.push(n);const n=arr[state.sequence[s]%arr.length];state.sequence[s]++;return{minuend:n,subtractor:s,extra:n-10,remain:10-s,answer:n-s}}
function stages(){const box=$('stageButtons');box.innerHTML='';for(let n=5;n<=9;n++){const locked=n>state.unlockedMax,b=document.createElement('button');b.type='button';b.className='stage-button'+(locked?' locked':'')+(n===state.selectedSubtractor?' active':'');b.disabled=locked;b.innerHTML=locked?`−${n}<small>🔒</small>`:`−${n}<small>${state.stageWins[n]}/3</small>`;b.onclick=()=>{state.selectedSubtractor=n;save();start()};box.appendChild(b)}const w=state.stageWins[state.selectedSubtractor];$('stageTitle').textContent=`−${state.selectedSubtractor} ステージ`;$('stageProgressText').textContent=state.selectedSubtractor===9&&w>=3?'ぜんぶクリア！🎉':state.selectedSubtractor===state.unlockedMax&&state.selectedSubtractor<9?`あと${Math.max(0,3-w)}もんで −${state.selectedSubtractor+1}`:`${w}/3 クリア`}
function theme(){const t=themes[state.theme]||themes.treasure,c=$('gameCard');c.classList.remove('treasure','lake','forest');c.classList.add(t.card);document.querySelectorAll('.theme-button').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$('sceneHero').textContent=t.hero;$('sceneTarget').textContent=t.target;$('takeToolEmoji').textContent=t.tool}
function ball(kind='neutral'){const d=document.createElement('span');d.className=`ball ${kind}`;return d}function fill(id,n,kind){const c=$(id);c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(ball(kind))}
function equation(html){const e=$('equation');e.innerHTML=html;e.classList.remove('flash');void e.offsetWidth;e.classList.add('flash')}
function show(n){phase=n;['splitStep','takeStep','mergeStep','resultStep'].forEach(id=>$(id).classList.add('hidden'));['step1','step2','step3'].forEach(id=>$(id).classList.remove('active','done'));if(n===1){$('splitStep').classList.remove('hidden');$('step1').classList.add('active')}else if(n===2){$('takeStep').classList.remove('hidden');$('step1').classList.add('done');$('step2').classList.add('active')}else if(n===3){$('mergeStep').classList.remove('hidden');$('step1').classList.add('done');$('step2').classList.add('done');$('step3').classList.add('active')}else{$('resultStep').classList.remove('hidden');$('step1').classList.add('done');$('step2').classList.add('done');$('step3').classList.add('done')}}
function prepareDrag(el,type){el.dataset.dragType=type;el.onpointerdown=startDrag;el.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&phase===Number(type==='split'?1:type==='take'?2:3)){e.preventDefault();auto(type)}};el.tabIndex=0}
function start(){clearTimers();cancelDrag();round=makeProblem(state.selectedSubtractor);save();stages();theme();$('starCount').textContent=state.stars;$('problemText').textContent=`${round.minuend} − ${round.subtractor}`;$('splitNumber').textContent=round.minuend;$('splitExtraNumber').textContent='？';$('takeMinus').textContent=`−${round.subtractor}`;$('takeToolCount').textContent=round.subtractor;$('parkExtraNumber').textContent=round.extra;$('mergeExtraNumber').textContent=round.extra;$('mergeRemainNumber').textContent=round.remain;$('mergeAnswerNumber').textContent='？';$('unlockMessage').classList.add('hidden');fill('wholeBalls',round.minuend,'neutral');fill('splitTenBalls',0,'ten');fill('splitExtraBalls',0,'extra');fill('takeTenBalls',10,'ten');fill('parkExtraBalls',round.extra,'extra');fill('mergeExtraBalls',round.extra,'extra');fill('mergeRemainBalls',round.remain,'ten');fill('mergeFinalBalls',0,'ten');fill('resultBalls',0,'ten');$('splitResult').classList.add('hidden');$('wholeGroup').classList.remove('faded');$('tenFrameTool').classList.remove('used');$('takeTool').classList.remove('used');$('takeTenBox').classList.remove('done');$('mergeExtraPack').classList.remove('used');$('mergeTarget').classList.remove('done');prepareDrag($('tenFrameTool'),'split');prepareDrag($('takeTool'),'take');prepareDrag($('mergeExtraPack'),'merge');equation(`${round.minuend} − ${round.subtractor} = <strong>？</strong>`);show(1)}
function pointIn(id,x,y){const r=$(id).getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function startDrag(e){if(e.button!==undefined&&e.button!==0)return;const el=e.currentTarget,type=el.dataset.dragType;if((type==='split'&&phase!==1)||(type==='take'&&phase!==2)||(type==='merge'&&phase!==3))return;e.preventDefault();cancelDrag();const ghost=el.cloneNode(true);ghost.removeAttribute('id');ghost.classList.add('drag-ghost');document.body.appendChild(ghost);drag={id:e.pointerId,el,type,ghost,x:e.clientX,y:e.clientY};move(e.clientX,e.clientY)}
function move(x,y){if(!drag)return;drag.x=x;drag.y=y;drag.ghost.style.left=`${x}px`;drag.ghost.style.top=`${y}px`;document.querySelectorAll('.drop-area').forEach(a=>a.classList.remove('hot'));const target=drag.type==='split'?'wholeGroup':drag.type==='take'?'takeTenBox':'mergeTarget';if(pointIn(target,x,y))$(target).classList.add('hot')}
function endDrag(){if(!drag)return;const {type,x,y,el}=drag,target=type==='split'?'wholeGroup':type==='take'?'takeTenBox':'mergeTarget';if(pointIn(target,x,y))auto(type);else{el.classList.remove('shake');void el.offsetWidth;el.classList.add('shake')}cancelDrag()}
function cancelDrag(){drag?.ghost?.remove();drag=null;document.querySelectorAll('.drop-area').forEach(a=>a.classList.remove('hot'))}
function auto(type){if(type==='split'&&phase===1)completeSplit();else if(type==='take'&&phase===2)completeTake();else if(type==='merge'&&phase===3)completeMerge()}
function completeSplit(){$('tenFrameTool').classList.add('used');$('wholeGroup').classList.add('faded');$('splitResult').classList.remove('hidden');fill('splitTenBalls',10,'ten');fill('splitExtraBalls',round.extra,'extra');$('splitExtraNumber').textContent=round.extra;equation(`${round.minuend} = <span class="tenText">10</span> + <span class="extraText">${round.extra}</span>`);later(()=>{equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + (10 − ${round.subtractor})`);show(2)},1250)}
function completeTake(){$('takeTool').classList.add('used');const balls=[...$('takeTenBalls').children];for(let i=0;i<round.subtractor;i++){later(()=>{balls[i].classList.add('fly');$('takeTool').classList.add('bump');later(()=>$('takeTool').classList.remove('bump'),120)},i*170)}later(()=>{for(let i=0;i<round.subtractor;i++)balls[i].remove();$('takeTenBox').classList.add('done');equation(`10 − ${round.subtractor} = <span class="tenText">${round.remain}</span>`);later(()=>{equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span>`);show(3)},950)},round.subtractor*170+250)}
function completeMerge(){$('mergeExtraPack').classList.add('used');$('mergeTarget').classList.add('done');$('mergeRemainBalls').innerHTML='';fill('mergeFinalBalls',round.extra,'extra');for(let i=0;i<round.remain;i++)$('mergeFinalBalls').appendChild(ball('ten'));$('mergeAnswerNumber').textContent=round.answer;equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span> = <strong>${round.answer}</strong>`);later(finish,1800)}
function finish(){show(4);const list=rewards[state.theme],idx=Math.floor(Math.random()*list.length),r=list[idx],bucket=state.collection[state.theme];bucket[idx]=(bucket[idx]||0)+1;state.stars++;state.stageWins[round.subtractor]=Math.min(3,state.stageWins[round.subtractor]+1);let unlock='';if(round.subtractor===state.unlockedMax&&state.stageWins[round.subtractor]>=3&&state.unlockedMax<9){state.unlockedMax++;unlock=`🎉 −${state.unlockedMax} が ひらいた！`}save();$('starCount').textContent=state.stars;$('resultEquation').innerHTML=`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span> = <strong>${round.answer}</strong>`;fill('resultBalls',round.extra,'extra');for(let i=0;i<round.remain;i++)$('resultBalls').appendChild(ball('ten'));$('rewardEmoji').textContent=r[0];$('rewardPrefix').textContent=themes[state.theme].prefix;$('rewardName').textContent=r[1];$('sceneTarget').textContent=r[0];$('unlockMessage').textContent=unlock;$('unlockMessage').classList.toggle('hidden',!unlock);stages()}
function renderCollection(){const list=rewards[book],owned=state.collection[book]||{},grid=$('collectionGrid');grid.innerHTML='';list.forEach((r,i)=>{const n=owned[i]||0,d=document.createElement('div');d.className='collection-item'+(n?' unlocked':'');d.innerHTML=`<span class="emoji">${r[0]}</span><strong>${n?r[1]:'？？？'}</strong><small>${n?'ゲット！':'まだだよ'}</small>${n?`<span class="collection-count">×${n}</span>`:''}`;grid.appendChild(d)});document.querySelectorAll('.collection-tab').forEach(b=>b.classList.toggle('active',b.dataset.collection===book))}
window.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.id){e.preventDefault();move(e.clientX,e.clientY)}},{passive:false});window.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.id)endDrag()});window.addEventListener('pointercancel',cancelDrag);window.addEventListener('blur',cancelDrag);
document.querySelectorAll('.theme-button').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;book=state.theme;save();start()});$('autoSplit').onclick=()=>auto('split');$('autoTake').onclick=()=>auto('take');$('autoMerge').onclick=()=>auto('merge');$('nextButton').onclick=()=>{if(state.stageWins[state.selectedSubtractor]>=3&&state.selectedSubtractor<state.unlockedMax)state.selectedSubtractor++;start()};const dialog=$('collectionDialog');$('collectionButton').onclick=()=>{book=state.theme;renderCollection();dialog.showModal()};$('closeCollectionButton').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};document.querySelectorAll('.collection-tab').forEach(b=>b.onclick=()=>{book=b.dataset.collection;renderCollection()});start();
})();