(()=>{'use strict';
const KEY='kurisagari-adventure-v1';
const rewards={treasure:[['🪙','ふるいコイン'],['🧭','ぼうけんコンパス'],['🏺','こだいのつぼ'],['💎','あおいほうせき'],['🗝️','おうごんのカギ'],['📜','ひみつのちず'],['👑','おうさまのかんむり'],['🏆','でんせつのトロフィー'],['💰','でんせつのたから']],lake:[['🐟','メダカ'],['🐠','カラフルフィッシュ'],['🐡','ぷくぷくフグ'],['🦀','カニさん'],['🦐','エビちゃん'],['🐙','ちびタコ'],['🦑','イカくん'],['🐬','イルカ'],['🐳','くじら']],forest:[['🐿️','リス'],['🐇','うさぎ'],['🦔','ハリネズミ'],['🦊','きつね'],['🦉','ふくろう'],['🦌','こじか'],['🐻','こぐま'],['🐼','パンダ'],['🦄','まぼろしユニコーン']]};
const themes={treasure:{card:'treasure',hero:'🏴‍☠️',target:'🧰',prefix:'おたからを みつけた！'},lake:{card:'lake',hero:'🎣',target:'🐟',prefix:'おさかなを つった！'},forest:{card:'forest',hero:'🦊',target:'🦊',prefix:'もりの なかまになった！'}};
const base={theme:'treasure',selectedSubtractor:5,unlockedMax:5,stageWins:{5:0,6:0,7:0,8:0,9:0},stars:0,sequence:{5:0,6:0,7:0,8:0,9:0},collection:{treasure:{},lake:{},forest:{}}};
const $=id=>document.getElementById(id);let state=load(),round=null,phase='split',extraMoved=0,removed=0,drag=null,book=state.theme;
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...p,stageWins:{...base.stageWins,...(p.stageWins||{})},sequence:{...base.sequence,...(p.sequence||{})},collection:{treasure:{...(p.collection?.treasure||{})},lake:{...(p.collection?.lake||{})},forest:{...(p.collection?.forest||{})}}}}catch{return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function makeProblem(s){const a=[];for(let n=11;n<=9+s;n++)a.push(n);const n=a[state.sequence[s]%a.length];state.sequence[s]++;return{minuend:n,subtractor:s,extra:n-10,remain:10-s,answer:n-s}}
function stages(){const box=$('stageButtons');box.innerHTML='';for(let n=5;n<=9;n++){const locked=n>state.unlockedMax,b=document.createElement('button');b.type='button';b.className='stage-button'+(locked?' locked':'')+(n===state.selectedSubtractor?' active':'');b.disabled=locked;b.innerHTML=locked?`−${n}<small>🔒</small>`:`−${n}<small>${state.stageWins[n]}/3</small>`;b.onclick=()=>{state.selectedSubtractor=n;save();start()};box.appendChild(b)}const w=state.stageWins[state.selectedSubtractor];$('stageTitle').textContent=`−${state.selectedSubtractor} ステージ`;$('stageProgressText').textContent=state.selectedSubtractor===9&&w>=3?'ぜんぶクリア！🎉':state.selectedSubtractor===state.unlockedMax&&state.selectedSubtractor<9?`あと${Math.max(0,3-w)}もんで −${state.selectedSubtractor+1}`:`${w}/3 クリア`}
function applyTheme(){const t=themes[state.theme]||themes.treasure,c=$('gameCard');c.classList.remove('treasure','lake','forest');c.classList.add(t.card);document.querySelectorAll('.theme-button').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$('sceneHero').textContent=t.hero;$('sceneTarget').textContent=t.target}
function equation(html){const el=$('equation');el.innerHTML=html;el.classList.remove('flash');void el.offsetWidth;el.classList.add('flash')}
function makeBall(kind='neutral',draggable=true){const b=document.createElement('button');b.type='button';b.className=`ball ${kind}`;b.setAttribute('aria-label','まるをうごかす');if(draggable){b.addEventListener('pointerdown',dragStart);b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();autoMove(b)}})}return b}
function fillStatic(id,n,kind){const c=$(id);c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(makeBall(kind,false))}
function renderSource(n){const c=$('sourceBalls');c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(makeBall('neutral',true))}
function updateCounts(){$('sourceCount').textContent=$('sourceBalls').children.length;$('extraCount').textContent=`${extraMoved}/${round.extra}`;$('subtractCount').textContent=`${removed}/${round.subtractor}`}
function setHint(step,text){$('hintBadge').textContent=step;$('hintText').textContent=text}
function start(){cancelDrag();round=makeProblem(state.selectedSubtractor);extraMoved=0;removed=0;phase='split';save();stages();applyTheme();$('starCount').textContent=state.stars;$('problemText').textContent=`${round.minuend} − ${round.subtractor}`;$('sourceTitle').textContent=`${round.minuend}こ`;$('extraNeed').textContent=round.extra;$('subtractNeed').textContent=round.subtractor;$('answerPanel').classList.add('hidden');$('resultInline').classList.add('hidden');$('extraArea').classList.add('pulse');$('subtractArea').classList.remove('pulse');renderSource(round.minuend);$('extraBalls').innerHTML='';$('subtractBalls').innerHTML='';updateCounts();setHint('①',`${round.extra}こ →`);equation(`${round.minuend} − ${round.subtractor} = <strong>？</strong>`)}
function dragStart(e){if(e.button!==undefined&&e.button!==0)return;if(phase!=='split'&&phase!=='subtract')return;const el=e.currentTarget;if(!el.isConnected)return;e.preventDefault();cancelDrag();const ghost=el.cloneNode(true);ghost.classList.add('drag-ghost');ghost.removeAttribute('id');document.body.appendChild(ghost);drag={id:e.pointerId,el,ghost,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY};moveDrag(e.clientX,e.clientY)}
function moveDrag(x,y){if(!drag)return;drag.x=x;drag.y=y;drag.ghost.style.left=`${x}px`;drag.ghost.style.top=`${y}px`;$('extraArea').classList.remove('hot');$('subtractArea').classList.remove('hot');const target=phase==='split'?'extraArea':'subtractArea';if(pointIn(target,x,y))$(target).classList.add('hot')}
function pointIn(id,x,y){const r=$(id).getBoundingClientRect();return x>=r.left&&x<=r.right&&y>=r.top&&y<=r.bottom}
function dragEnd(){if(!drag)return;const {el,x,y,startX,startY}=drag,target=phase==='split'?'extraArea':'subtractArea',distance=Math.hypot(x-startX,y-startY);if(pointIn(target,x,y)||distance<9)autoMove(el);else{el.classList.remove('wrong');void el.offsetWidth;el.classList.add('wrong')}cancelDrag()}
function cancelDrag(){drag?.ghost?.remove();drag=null;$('extraArea')?.classList.remove('hot');$('subtractArea')?.classList.remove('hot')}
function autoMove(el){if(!el||!el.isConnected)return;if(phase==='split')moveToExtra(el);else if(phase==='subtract')moveToSubtract(el)}
function moveToExtra(el){if(extraMoved>=round.extra)return;el.remove();$('extraBalls').appendChild(makeBall('extra',false));extraMoved++;updateCounts();if(extraMoved===round.extra){phase='subtract';[...$('sourceBalls').children].forEach(b=>{b.classList.add('ten')});$('extraArea').classList.remove('pulse');$('subtractArea').classList.add('pulse');setHint('②',`↓ ${round.subtractor}こ`);equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + (10 − ${round.subtractor})`)}}
function moveToSubtract(el){if(removed>=round.subtractor)return;el.remove();$('subtractBalls').appendChild(makeBall('removed',false));removed++;updateCounts();if(removed===round.subtractor){phase='answer';$('subtractArea').classList.remove('pulse');setHint('③','こたえは？');equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span> = <strong>？</strong>`);showAnswers()}}
function showAnswers(){const panel=$('answerPanel'),box=$('answers');box.innerHTML='';for(let n=1;n<=9;n++){const b=document.createElement('button');b.type='button';b.className='answer-button';b.textContent=n;b.addEventListener('click',()=>chooseAnswer(n,b));box.appendChild(b)}panel.classList.remove('hidden')}
function chooseAnswer(n,b){if(phase!=='answer')return;if(n!==round.answer){b.classList.remove('wrong');void b.offsetWidth;b.classList.add('wrong');return}phase='result';b.classList.add('correct');[...$('answers').children].forEach(x=>x.disabled=true);finish()}
function finish(){equation(`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span> = <strong>${round.answer}</strong>`);const list=rewards[state.theme],idx=Math.floor(Math.random()*list.length),reward=list[idx],bucket=state.collection[state.theme];bucket[idx]=(bucket[idx]||0)+1;state.stars++;state.stageWins[round.subtractor]=Math.min(3,state.stageWins[round.subtractor]+1);let unlock='';if(round.subtractor===state.unlockedMax&&state.stageWins[round.subtractor]>=3&&state.unlockedMax<9){state.unlockedMax++;unlock=`🎉 −${state.unlockedMax} が ひらいた！`}save();$('starCount').textContent=state.stars;$('resultEquation').innerHTML=`${round.minuend} − ${round.subtractor} = <span class="extraText">${round.extra}</span> + <span class="tenText">${round.remain}</span> = <strong>${round.answer}</strong>`;$('resultBalls').innerHTML='';for(let i=0;i<round.extra;i++)$('resultBalls').appendChild(makeBall('extra',false));for(let i=0;i<round.remain;i++)$('resultBalls').appendChild(makeBall('ten',false));$('rewardEmoji').textContent=reward[0];$('rewardPrefix').textContent=themes[state.theme].prefix;$('rewardName').textContent=reward[1];$('sceneTarget').textContent=reward[0];$('unlockMessage').textContent=unlock;$('unlockMessage').classList.toggle('hidden',!unlock);$('resultInline').classList.remove('hidden');stages()}
function renderCollection(){const list=rewards[book],owned=state.collection[book]||{},grid=$('collectionGrid');grid.innerHTML='';list.forEach((r,i)=>{const n=owned[i]||0,d=document.createElement('div');d.className='collection-item'+(n?' unlocked':'');d.innerHTML=`<span class="emoji">${r[0]}</span><strong>${n?r[1]:'？？？'}</strong><small>${n?'ゲット！':'まだだよ'}</small>${n?`<span class="collection-count">×${n}</span>`:''}`;grid.appendChild(d)});document.querySelectorAll('.collection-tab').forEach(b=>b.classList.toggle('active',b.dataset.collection===book))}
window.addEventListener('pointermove',e=>{if(drag&&e.pointerId===drag.id){e.preventDefault();moveDrag(e.clientX,e.clientY)}},{passive:false});window.addEventListener('pointerup',e=>{if(drag&&e.pointerId===drag.id)dragEnd()});window.addEventListener('pointercancel',cancelDrag);window.addEventListener('blur',cancelDrag);
document.querySelectorAll('.theme-button').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;book=state.theme;save();start()});$('nextButton').onclick=start;const dialog=$('collectionDialog');$('collectionButton').onclick=()=>{book=state.theme;renderCollection();dialog.showModal()};$('closeCollectionButton').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};document.querySelectorAll('.collection-tab').forEach(b=>b.onclick=()=>{book=b.dataset.collection;renderCollection()});start();
})();