(()=>{'use strict';
const KEY='kurisagari-adventure-v1';
const rewards={lake:[['🐟','メダカ'],['🐠','カラフルフィッシュ'],['🐡','ぷくぷくフグ'],['🦀','カニさん'],['🦐','エビちゃん'],['🐙','ちびタコ'],['🦑','イカくん'],['🐬','イルカ'],['🐳','くじら']],forest:[['🐿️','リス'],['🐇','うさぎ'],['🦔','ハリネズミ'],['🦊','きつね'],['🦉','ふくろう'],['🦌','こじか'],['🐻','こぐま'],['🐼','パンダ'],['🦄','まぼろしユニコーン']]};
const base={theme:'lake',selectedSubtractor:5,unlockedMax:5,stageWins:{5:0,6:0,7:0,8:0,9:0},stars:0,sequence:{5:0,6:0,7:0,8:0,9:0},collection:{lake:{},forest:{}}};
const $=id=>document.getElementById(id);let state=load(),round,phase=1,given=0,drag=null,book='lake';
function load(){try{const p=JSON.parse(localStorage.getItem(KEY)||'{}');return {...base,...p,stageWins:{...base.stageWins,...(p.stageWins||{})},sequence:{...base.sequence,...(p.sequence||{})},collection:{lake:{...(p.collection?.lake||{})},forest:{...(p.collection?.forest||{})}}}}catch{return JSON.parse(JSON.stringify(base))}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function problem(s){const a=[];for(let n=11;n<=9+s;n++)a.push(n);const n=a[state.sequence[s]%a.length];state.sequence[s]++;return{minuend:n,subtractor:s,extra:n-10,remain:10-s,answer:n-s}}
function stages(){const box=$('stageButtons');box.innerHTML='';for(let n=5;n<=9;n++){const b=document.createElement('button'),locked=n>state.unlockedMax;b.type='button';b.className='stage-button'+(locked?' locked':'')+(n===state.selectedSubtractor?' active':'');b.disabled=locked;b.innerHTML=locked?`−${n}<small>🔒</small>`:`−${n}<small>${state.stageWins[n]}/3</small>`;b.onclick=()=>{state.selectedSubtractor=n;save();start()};box.appendChild(b)}$('stageTitle').textContent=state.unlockedMax===5?'まずは −5':`−${state.selectedSubtractor} に ちょうせん`;const w=state.stageWins[state.selectedSubtractor];$('stageProgressText').textContent=state.selectedSubtractor===9&&w>=3?'ぜんぶ クリア！🎉':state.selectedSubtractor===state.unlockedMax&&state.selectedSubtractor<9?`あと${Math.max(0,3-w)}もんで −${state.selectedSubtractor+1}`:`${w}/3 できたよ`}
function token(draggable=false){const d=document.createElement('div');d.className='token'+(draggable?' draggable':'');if(draggable){d.tabIndex=0;d.setAttribute('role','button');d.setAttribute('aria-label','1こ運ぶ');d.addEventListener('pointerdown',dragStart);d.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();give(d)}})}return d}
function fill(id,n,draggable=false){const c=typeof id==='string'?$(id):id;c.innerHTML='';for(let i=0;i<n;i++)c.appendChild(token(draggable))}
function theme(){const f=state.theme==='forest';$('gameCard').classList.toggle('forest',f);$('gameCard').classList.toggle('lake',!f);document.querySelectorAll('.theme-button').forEach(b=>b.classList.toggle('active',b.dataset.theme===state.theme));$('rewardCharacter').textContent=f?'🦊':'🐟';$('dropTargetEmoji').textContent=f?'🦊':'🐟';$('actionVerb').textContent=f?'なかま':'おさかな';$('dropTargetText').textContent=f?'ここへ あげよう！':'ここへ はこぼう！'}
function step(n){phase=n;['stepOne','stepTwo','stepThree','resultStep'].forEach(x=>$(x).classList.add('hidden'));['stepDot1','stepDot2','stepDot3'].forEach(x=>$(x).classList.remove('active','done'));if(n===1){$('stepOne').classList.remove('hidden');$('stepDot1').classList.add('active')}else if(n===2){$('stepTwo').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('active')}else if(n===3){$('stepThree').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('done');$('stepDot3').classList.add('active')}else{$('resultStep').classList.remove('hidden');$('stepDot1').classList.add('done');$('stepDot2').classList.add('done');$('stepDot3').classList.add('done')}}
function start(){cancelDrag();given=0;round=problem(state.selectedSubtractor);save();theme();stages();$('starCount').textContent=state.stars;$('problemText').textContent=`${round.minuend} − ${round.subtractor} = ?`;$('splitSentence').innerHTML=`${round.minuend}は <strong>10</strong> と <strong>${round.extra}</strong> だね！`;$('extraCountLabel').textContent=`${round.extra}こ`;$('takeHeading').textContent=`② 10この中から ${round.subtractor}こ つかおう`;$('takeInstructionCount').textContent=`${round.subtractor}こ`;$('givenCounter').textContent=`0 / ${round.subtractor}こ`;$('speechBubble').textContent=state.theme==='forest'?`木の実を ${round.subtractor}こ ちょうだい！`:`エサを ${round.subtractor}こ つかうよ！`;$('remainSentence').innerHTML=`10 − ${round.subtractor} で、<strong>${round.remain}こ</strong> のこったよ。`;$('remainCount').textContent=`${round.remain}こ`;$('mergeExtraCount').textContent=`${round.extra}こ`;fill('tenTokens',10);fill('extraTokens',round.extra);fill('dragTokens',10,true);fill('remainTokens',round.remain);fill('mergeExtraTokens',round.extra);$('tenBox').classList.remove('highlight');step(1)}
function begin(){const b=$('tenBox');b.classList.remove('highlight');void b.offsetWidth;b.classList.add('highlight');setTimeout(()=>step(2),420)}
function dragStart(e){if(phase!==2||given>=round.subtractor||e.currentTarget.classList.contains('given'))return;e.preventDefault();const t=e.currentTarget,g=t.cloneNode();g.className='token drag-ghost';document.body.appendChild(g);drag={id:e.pointerId,token:t,ghost:g};t.setPointerCapture(e.pointerId);move(e.clientX,e.clientY);t.addEventListener('pointermove',dragMove);t.addEventListener('pointerup',dragEnd,{once:true});t.addEventListener('pointercancel',dragEnd,{once:true})}
function move(x,y){if(!drag)return;drag.ghost.style.left=`${x}px`;drag.ghost.style.top=`${y}px`}
function inside(e){const r=$('dropTarget').getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom}
function dragMove(e){if(!drag||drag.id!==e.pointerId)return;move(e.clientX,e.clientY);$('dropTarget').classList.toggle('hot',inside(e))}
function dragEnd(e){if(!drag||drag.id!==e.pointerId)return;const ok=inside(e),t=drag.token;cancelDrag();if(ok)give(t)}
function cancelDrag(){if(!drag)return;drag.token.removeEventListener('pointermove',dragMove);drag.ghost.remove();$('dropTarget').classList.remove('hot');drag=null}
function give(t){if(phase!==2||given>=round.subtractor)return;if(!t)t=[...$('dragTokens').children].find(x=>!x.classList.contains('given'));if(!t||t.classList.contains('given'))return;t.classList.add('given');given++;$('givenCounter').textContent=`${given} / ${round.subtractor}こ`;const c=$('rewardCharacter');c.classList.remove('bounce');void c.offsetWidth;c.classList.add('bounce');const left=round.subtractor-given;if(left)$('speechBubble').textContent=`あと ${left}こ！`;else{$('speechBubble').textContent=`ありがとう！ ${round.remain}こ のこったね！`;setTimeout(()=>step(3),500)}}
function finish(){step(4);const list=rewards[state.theme],idx=Math.floor(Math.random()*list.length),r=list[idx],bucket=state.collection[state.theme];bucket[idx]=(bucket[idx]||0)+1;state.stars++;state.stageWins[round.subtractor]=Math.min(3,state.stageWins[round.subtractor]+1);let unlock='';if(round.subtractor===state.unlockedMax&&state.stageWins[round.subtractor]>=3&&state.unlockedMax<9){state.unlockedMax++;state.selectedSubtractor=state.unlockedMax;unlock=`🎉 −${state.unlockedMax} のステージが ひらいたよ！`}save();$('starCount').textContent=state.stars;$('resultEquation').textContent=`${round.minuend} − ${round.subtractor} = ${round.answer}`;$('methodEquation').textContent=`10 − ${round.subtractor} = ${round.remain}　→　${round.remain} ＋ ${round.extra} = ${round.answer}`;$('rewardEmoji').textContent=r[0];$('rewardName').textContent=r[1];$('rewardPrefix').textContent=state.theme==='forest'?'もりの なかまになった！':'おさかなを つった！';$('rewardCharacter').textContent=r[0];$('speechBubble').textContent=state.theme==='forest'?'また あそぼうね！':'つれたー！';$('unlockMessage').classList.toggle('hidden',!unlock);$('unlockMessage').textContent=unlock;stages()}
function toast(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1500)}
function collection(){const list=rewards[book],owned=state.collection[book],grid=$('collectionGrid');grid.innerHTML='';list.forEach((r,i)=>{const n=owned[i]||0,d=document.createElement('div');d.className='collection-item'+(n?' unlocked':'');d.innerHTML=`<span class="emoji">${r[0]}</span><strong>${n?r[1]:'？？？'}</strong><small>${n?'ゲット！':'まだ あってないよ'}</small>${n?`<span class="collection-count">×${n}</span>`:''}`;grid.appendChild(d)});document.querySelectorAll('.collection-tab').forEach(b=>b.classList.toggle('active',b.dataset.collection===book))}
document.querySelectorAll('.theme-button').forEach(b=>b.onclick=()=>{state.theme=b.dataset.theme;save();start();toast(state.theme==='forest'?'🌳 もりへ しゅっぱつ！':'🎣 みずうみへ しゅっぱつ！')});$('foundTenButton').onclick=begin;$('giveOneButton').onclick=()=>give();$('mergeButton').onclick=finish;$('nextButton').onclick=start;const dialog=$('collectionDialog');$('collectionButton').onclick=()=>{book=state.theme;collection();dialog.showModal()};$('closeCollectionButton').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close()};document.querySelectorAll('.collection-tab').forEach(b=>b.onclick=()=>{book=b.dataset.collection;collection()});window.addEventListener('blur',cancelDrag);window.addEventListener('pointerup',e=>{if(drag&&drag.id===e.pointerId)dragEnd(e)});start();
})();